# https://github.com/nickjj/ansible-user
---

# - name: Create user for the app
#   ansible.builtin.import_role:
#     name: "create.user"  
#   tags:
#     - user
#   vars: 
#     - user_groups: 
#       - "{{app_user_group}}"
#     - user_name: "{{app_user_name}}"
#     - user_shell: "/bin/bash"
#     - user_generate_ssh_key: False
#     - user_local_ssh_key_path: ""
# # Do you want to enable running root commands without needing a password?
#     - user_enable_passwordless_sudo: True

# - name: Update apt repo and cache
#   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
# - name: Install nodejs and npm
#   apt: "name={{ item }} state=present"    
#   with_items:
#     - nodejs
#     - npm

# - name: Install PM2 
#   community.general.npm:
#     name: " {{ item }}"
#     global: true
#   with_items: 
#      - pm2
#      - yarn 

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    
- name: install nvm 
  ansible.builtin.shell: nvm install 20.15.1

- name: install nvm 
  ansible.builtin.shell: nvm use node

- name: Rsync files
  become: true
  become_user: "{{app_user_name}}"
  ansible.posix.synchronize:
    src: ../now3news/    
    dest: "{{app_dir}}"
    rsync_opts: 
      - "-FF"
    
- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ app_name }}"
  become: yes
  become_user: postgres

- name: npm ci 
  become: true
  become_user: "{{app_user_name}}"
  ansible.builtin.shell: npm ci 
  args:
    chdir: "{{app_dir}}"  

- name: run db migrations
  become: true
  become_user: "{{app_user_name}}"
  ansible.builtin.shell: npm run k:migrate
  args:
    chdir: "{{app_dir}}"  

# - name: Copy ecosystem file
#   become: true
#   become_user: "{{app_user_name}}"
#   ansible.builtin.template:
#     src: ecosystem.config.js.j2
#     dest: "{{app_dir}}/ecosystem.config.js"

# - name: Start pm2
#   become: true
#   become_user: "{{app_user_name}}"
#   ansible.builtin.shell: pm2 restart     
#   args:
#     chdir: "{{app_dir}}"
     