---
- name: Update web servers
  hosts: all
  vars_files:
    - ./vars/main.yml

  tasks:
    # - name: Update apt repo and cache  
    #   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 # Update apt repository and cache
    # - name: Install nodejs and npm 
    #   apt:                        # Install Node.js and NPM
    #     pkg:
    #     - nodejs
    #     - npm
    # - name: install nginx
    #   apt: name=nginx state=latest

    # - name: start nginx
    #   service:
    #       name: nginx
    #       state: started

    # - name: Create directory for static content
    #   file:
    #     path: /var/www/html/weaver-portfolio
    #     state: directory
    #     mode: 0755

    # - name: Create directory for static content
    #   file:
    #     path: /var/www/html/blog
    #     state: directory
    #     mode: 0755        

    # - name: Copy nginx config file
    #   # become: yes
    #   copy:
    #     src: server_nginx_conf
    #     dest: /etc/nginx/sites-available/weaver-portfolio
    #     # owner: "nginx"

    # - name: Enable default Nginx website
    #   file:
    #     src: /etc/nginx/sites-available/weaver-portfolio
    #     path: /etc/nginx/sites-enabled/weaver-portfolio
    #     state: link 

    - name: Copy file with owner and permission, using symbolic representation
      ansible.posix.synchronize:
        src: ../diary/.app/dist/
        dest: /var/www/html/blog        

    - name: restart nginx
      service:
          name: nginx
          state: restarted

  
  #  - name: Print message
  #    ansible.builtin.debug:
  #     msg: Hello world

  # tasks:    
  

  #   - name: Expose the site
  #     become: yes
  #     file: src=/etc/nginx/sites-available/server dest=/etc/nginx/sites-enabled/server state=link

  #   - name: Restart nginx
  #     become: yes
  #     service:
  #       name: nginx
  #       state: started

  # roles:
  #   - geerlingguy.nodejs

  # vars:
    # backup_profiles:
    #   - name: postgresql
    #     schedule: 0 4 * * *
    #     source: postgresql://weaver-prod
    #     target: file:///tmp
    #     user: postgres
