---
- name: Install oldweaver apps
  hosts: all
  vars_files:
    - ./vars/main.yml

  tasks:   
    # - name: Install firewall tools 
    #   apt: 
    #     pkg:
    #     - iptables-persistent 
    #     - net-tools 

    # - name: Copy firewall state
    #   ansible.builtin.copy:
    #     src: files/firewall/iptables-saved.txt
    #     dest: "{{iptables_state_file}}"    

    # - name: harden port 80  using firewall
    #   ansible.builtin.shell: iptables -F INPUT && iptables-restore "{{iptables_state_file}}" 

  roles:
    # - geerlingguy.swap 
    - blog
    # - db
    # - luther #sanbox app.
    # - n3n


  