---
- name: Install oldweaver apps
  hosts: all
  vars_files:
    - ./vars/main.yml

  # tasks: 
  

  # - name: install nginx
  #   apt: name=nginx state=latest

  roles:
    # - blog
    - luther #sanbox app.
    # - geerlingguy.swap #sanbox app.


  