// This file was generated by a custom prisma generator, do not edit manually.
export const CommentableType = {
  Todo: "Todo",
} as const;

export type CommentableType = (typeof CommentableType)[keyof typeof CommentableType];
